inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
